# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yuxin Liang
title: 
email: 	liangyuxin42@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile-photo.jpg
about_content: | # this will include new lines to allow paragraphs

  Hi, my name is Liang Yuxin. I am a master's student in computer science from Northwestern University. 
  My research interests are in <mark>natural language processing</mark> and <mark>representation learning</mark>. 
  
  
  During my master's study, I was introduced to and fascinated by the rich and exciting field of natural language processing. 
  My research work centers around text representation learning (some of which has been published). 
  In this process I have also acquired some essential skills, including literature searching and reading, programming (mainly in python and pytorch), and the ability to communicate with people in depth about academic subjects. 
  
  I hope to continue the fascinating and challenging research journey during my PhD!
  
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education and Experience
    layout: list
    content:
      - layout: top-left
        title: M.S. in Software Engineering
        sub_title: Northwest University
        caption: 2019.09 - Present
        description: | # this will include new lines to allow paragraphs
          #### Research
          - Research Topic: Natural Language Processing, Representation Learning
          
          - During my master’s program at Northwest University, my research work was focused on representation learning of text, especially on the geometry of the representation. My work can be divided into three main subdivisions.
          
          - Firstly, **the geometric properties of word embeddings of pre-trained language models** such as BERT are investigated and it is found that such word embeddings occupy only a low-dimensional subspace of the representation space (representation degradation problem). 
          My work, which was accepted by ICANN2021, optimizes word embeddings by removing dominant directions to make them more isotropic and improve their task performance.
          
          - I also work on **optimizing the text representation of pre-trained models using unsupervised contrast learning**, by performing data augmentation on large-scale unlabeled text and porting the two-branch structure commonly used in CV. 
          This work has been submitted to ACL 2022.
          
          - Besides, I am also interested in **using different losses in text classification tasks to improve the learned text representation** and have tried to use MCR2 loss in CV for text classification and <a href="https://slideslive.com/38955582/applying-maximal-coding-rate-reduction-to-text-classification">presented at the journe@MLSys2021 workshop</a>.
          
          - During the research process, I not only increased my understanding of the field, but also learned some important research skills, including searching and reading literature, designing experiments and writing code to execute them, communicating with people in-depth about academic subjects, writing and presenting papers, and so on.
          
          - It has been a fulfilling journey, but in the process of gaining knowledge and skills, I feel that there is not less but more to learn. 
          During the Ph.D. process, I hope to go further in my research work, including but not limited to learning how to **get to the bottom of a certain problem**, how to use mathematical tools to solve research problems, and how to communicate and collaborate more effectively.
          
          #### Others
          - Besides my research work, I also served as a teaching assistant for undergraduate programming courses, including teaching the experimental section, grading assignments, and answering questions.
     
      - layout: top-left
        title: Physics Teacher
        sub_title: New Oriental Education & Technology Group Inc.
        caption: 2019.05 - 2019.09
        description: | # this will include new lines to allow paragraphs
          - I worked briefly as a middle school teacher in an educational institution, teaching physics for two classes, including theoretical knowledge and experimental operations. 
          Despite the short time, I learned a lot of presentation skills, such as how to use relevant questions and stories to capture the audience's attention, how to control body language, etc.
          
      - layout: top-left
        title: Defect Analysis Engineer
        sub_title: Samsung Suzhou LCD Co., Ltd.
        caption: 2015.07 - 2017.10 
        description: | # this will include new lines to allow paragraphs
          - After I graduated with my bachelor's degree, I worked for Samsung for two years. 
          I was responsible for the analysis of product defects and assisting the manufacturing department in solving the defects. 
          In addition to the physical and chemical analysis techniques, I also learned during these two years how to analyze a specific problem (such as the cause of a specific product defect) and how to work with people in a complex system to solve a problem. 
          This has been of great benefit to my later work and research.
      
      - layout: top-left
        title: B.S. in Nanomaterials and Technology
#         sub_title: 
        caption: 2011.09-2015.06 in Nanjing University of Science and Technology
        description: | # this will include new lines to allow paragraphs   
          - I studied at Nanjing University of Science and Technology for my undergraduate degree, majoring in nanomaterial. 
          The main topics of study include condensed matter physics, semiconductor materials, and nanomaterials. 
          This has little to do with my current research, but an outsider's perspective sometimes brings new ideas. 
          Also, I gained a good foundation in mathematics and physics during my undergraduate studies.
          
  - title: Publications and Conferences
    layout: text
    content: | # this will include new lines to allow paragraphs
      [1] Yuxin Liang, Rui Cao, Jie Zheng*, Jie Ren, and Ling Gao. <a href="https://arxiv.org/abs/2104.05274">Learning to Remove: Towards Isotropic Pre-trained BERT Embedding.</a> In International Conference on Artificial Neural Networks. Full Paper.
      
      [2] Yuxin Liang, Rui Cao, Ling Gao, and Jie Zheng*. Applying Maximal Coding Rate Reduction to Text classification. In Conference on Machine Learning and Systems. Workshop.
        
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Research experience in deep learning and natural language processing
      - Proficiency in python programming and pytorch framework (<a href="https://github.com/liangyuxin42">some projects here</a>)
      - Proficiency in reading, writing and oral communication in English (IELTS 7.5)
      
  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - First-Class Academic Scholarship, Northwest University, 2019
      - First-Class Academic Scholarship, Northwest University, 2020
      - Second Prize of the 17th China Graduate Student Mathematical Modeling Competition
      - Third Prize of the 15th China Postgraduate Electronic Design Competition in Northwest Region
 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not reading papers or coding, I also enjoy hiking and digital painting.
      
      <a href="https://liangyuxin42.github.io/gallery/index.html">Here are some of my digital painting works!</a>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
